title: Jax Young's Blog
author:
  name: Jax Young
  email: jaxvanyang@gmail.com
description: >-
  一名游戏和 Linux 爱好者。
baseurl: ""
url: "https://jaxvanyang.github.io"
lang: zh-Hans

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      author: "Jax Young"
  - scope:
      path: "_drafts"
    values:
      layout: "post"
      author: "Jax Young"

# Minima settings
minima:
  skin: tokyo-night
  # show_excerpts: true
  date_format: "%Y-%m-%d"
  social_links:
    - title: Jax Young at GitHub
      icon: github
      url: "https://github.com/jaxvanyang"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  quiet_deps: true
  silence_deprecations: [import]

